/**
 * @ Author: Marshall Telaumbanua
 * @ Create Time: 2023-06-07 19:52:33
 * @ Usage: CALL MWCONFIG.MERGE_PARSER_CODEX(PARSER_ID, ID, CODEX_ID)
 */

CREATE OR REPLACE PROCEDURE MERGE_PARSER_CODEX (
	IN PARSER_ID VARCHAR(256),
	IN ID VARCHAR(256),
	IN CODEX_ID VARCHAR(256),
	IN MODIFIED_BY VARCHAR(64) DEFAULT CURRENT_USER,
	IN TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
LANGUAGE SQL
BEGIN
	DECLARE SQL_STMT VARCHAR(10000);

	SET SQL_STMT = 'MERGE INTO MWCONFIG.PARSER_CODEX AS T ' ||
		'USING (VALUES (''' || PARSER_ID || ''', ''' || ID || ''', ''' || CODEX_ID || ''', ''' || MODIFIED_BY || ''', ''' || TIMESTAMP || ''')) AS S (PARSER_ID, ID, CODEX_ID, MODIFIED_BY, TIMESTAMP) ' ||
		'ON (T.PARSER_ID = S.PARSER_ID AND T.ID = S.ID) ' ||
		'WHEN MATCHED THEN ' ||
		'  UPDATE SET ' ||
		'    T.CODEX_ID = S.CODEX_ID, ' ||
		'    T.MODIFIED_BY = S.MODIFIED_BY, ' ||
		'    T.TIMESTAMP = S.TIMESTAMP ' ||
		'WHEN NOT MATCHED THEN ' ||
		'  INSERT (PARSER_ID, ID, CODEX_ID, MODIFIED_BY, TIMESTAMP) ' ||
		'  VALUES (S.PARSER_ID, S.ID, S.CODEX_ID, S.MODIFIED_BY, S.TIMESTAMP)';

	PREPARE STMT FROM SQL_STMT;
	EXECUTE STMT;
END
@
